engines:
  eslint:
    enabled: true
    config:
      extensions:
      - .es6
      - .js
ratings:
   paths:
   - server/**
   - config/**
   - "**.js"
exclude_paths:
- node_modules/**/*
- server/tests/**
