---
swagger: "2.0"
info:
  description: "GobHash.Inc"
  version: "1.0.0"
  title: "Private API"
basePath: "/v1"
schemes:
- "http"
consumes:
  - application/json
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
produces:
- "application/json"
paths:
  /auth/login:
    post:
      tags:
      - "Auth"
      summary: "Login user"
      description: "Login endpoint"
      operationId: "postLogin"
      parameters:
      - name: "loginBody"
        in: "body"
        description: "Login object"
        required: true
        schema:
          $ref: "#/definitions/Login"

      responses:
        200:
          description: "Authorization Token"
          schema:
            type: "string"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
  /auth/random-number:
    get:
      security:
        - Bearer: []
      tags:
      - "Auth"
      summary: "Get random number"
      description: "Test Protected route"
      operationId: "authRandomGET"
      responses:
        200:
          description: "User Token and Random number"
          schema:
            type: "string"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
  /auth/reset:
    post:
      tags:
      - "Auth"
      summary: "Request to reset password"
      description: "Initial flow to reset a users's password. Sends email to user."
      operationId: "authResetPOST"
      parameters:
      - name: "AuthBody"
        in: "body"
        description: "Auth Reset body"
        required: true
        schema:
          $ref: "#/definitions/Auth"

      responses:
        200:
          description: "Reset token"
          schema:
            type: "object"
            $ref: "#/definitions/ResetPassword"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
  /auth/reset/{token}:
    get:
      security:
        - Bearer: []
      tags:
      - "Auth"
      summary: "Validate token in URL"
      description: "Search for valid valid reset token. Returns user object"
      operationId: "validateResetPOST"
      parameters:
      - name: "token"
        in: "path"
        description: "Reset password token"
        required: true
        type: "string"
      responses:
        200:
          description: "Reset token"
          schema:
            type: "object"
            $ref: "#/definitions/User"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
  /users:
    get:
      security:
        - Bearer: []
      tags:
      - "User"
      summary: "Get all users"
      description: "List all registered users."
      operationId: "listUsersGET"
      parameters:
      - name: "skip"
        in: "query"
        description: "Skip users (offset)"
        required: false
        type: "number"
      - name: "limit"
        in: "query"
        description: "Limit user list"
        required: false
        type: "number"
      responses:
        200:
          description: "User"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
    post:
      tags:
      - "User"
      summary: "Create new user"
      description: "Create a new user."
      operationId: "createUserPOST"
      parameters:
      - name: "bodyUser"
        in: "body"
        required: true
        schema:
          $ref: "#/definitions/UserPost"
      responses:
        200:
          description: "User"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
    put:
      security:
        - Bearer: []
      tags:
      - "User"
      summary: "Update a user"
      description: "Update a user's password and email"
      operationId: "updateUserPUT"
      parameters:
      - name: "bodyUser"
        in: "body"
        required: true
        schema:
          $ref: "#/definitions/UserPut"
      responses:
        200:
          description: "User"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"


  /users/{id}:
    get:
      security:
        - Bearer: []
      tags:
      - "User"
      summary: "Get User by id"
      description: "Get user by id"
      operationId: "userGET"
      parameters:
      - name: "id"
        in: "path"
        description: "User id"
        required: true
        type: "string"
      responses:
        200:
          description: "User"
          schema:
            type: "object"
            $ref: "#/definitions/User"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
    delete:
      security:
        - Bearer: []
      tags:
      - "User"
      summary: "Delete a user"
      description: "Delete a user by id"
      operationId: "deleteUser"
      parameters:
      - name: "id"
        in: "path"
        required: true
        description: "User's id"
        type: number
      responses:
        200:
          description: "User"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
  /users/password/change:
    post:
      security:
        - Bearer: []
      tags:
      - "User"
      summary: Change a user's password
      description: Change user's password and remove reset token
      operationId: changePasswordPost
      parameters:
      - name: "bodyPassword"
        in: "body"
        description: "body Password"
        required: true
        schema:
          $ref: "#/definitions/passwordChange"
      responses:
        200:
          description: "Password changed message"
          schema:
            type: "string"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
  /users/biography:
    post:
      tags:
      - "User"
      summary: "Update or set the user's biography"
      description: "This will create or update the user's biography."
      operationId: "userBioPOST"
      parameters:
      - name: "UserBody"
        in: "body"
        description: "User biography body"
        required: true
        schema:
          $ref: "#/definitions/UserBio"

      responses:
        200:
          description: "biography updated"
          schema:
            type: "string"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
  /users/picture:
    post:
      tags:
      - "User"
      summary: Uploads a file.
      consumes:
       - multipart/form-data
      parameters:
       - in: formData
         name: profile
         type: file
         description: The photo to upload.
      responses:
        200:
          description: "biography updated"
          schema:
            type: "string"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
  /users/follow:
    post:
      tags:
      - "User"
      summary: Follow a user.
      parameters:
      - name: "FollowBody"
        in: "body"
        description: "Follow another user"
        required: true
        schema:
          $ref: "#/definitions/UserFollow"
      responses:
        200:
          description: "user followed user"
          schema:
            type: "string"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
  /users/unfollow:
    post:
      tags:
      - "User"
      summary: Unfollows a user.
      parameters:
      - name: "FollowBody"
        in: "body"
        description: "Unfollows another user"
        required: true
        schema:
          $ref: "#/definitions/UserFollow"
      responses:
        200:
          description: "user unfollowed user"
          schema:
            type: "string"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
  /post/:
    post:
      security:
        - Bearer: []
      tags:
      - "Post"
      summary: Create a new post
      description: Create a new post
      operationId: createNewPost
      parameters:
      - name: "PostBody"
        in: "body"
        description: "body of post"
        required: true
        schema:
          $ref: "#/definitions/PostBody"
      responses:
        200:
          description: "Post created"
          schema:
            type: "object"
            $ref: "#/definitions/PostBody"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
    get:
      security:
        - Bearer: []
      tags:
      - "Post"
      summary: Get list of posts
      description: Get list of posts
      operationId: GetPOST
      parameters:
      - name: "skip"
        in: "query"
        description: "Skip posts (offset)"
        required: false
        type: "number"
      - name: "limit"
        in: "query"
        description: "Limit post list"
        required: false
        type: "number"
      responses:
        200:
          description: "Post created"
          schema:
            type: "object"
            $ref: "#/definitions/PostEntity"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
  /post/{postId}:
     get:
      security:
        - Bearer: []
      tags:
      - "Post"
      summary: Get one post
      description: Get post by id
      operationId: GetPOST
      parameters:
      - name: "postId"
        in: "path"
        description: "Post id"
        required: true
        type: "string"
      responses:
        200:
          description: "Post created"
          schema:
            type: "object"
            $ref: "#/definitions/PostEntity"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
definitions:
  Login:
    type: "object"
    properties:
      username:
        type: "string"
      password:
        type: "string"
  Auth:
    type: "object"
    properties:
      username:
        type: "string"
      email:
        type: "string"

  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      username:
        type: "string"
  UserPost:
    type: "object"
    properties:
      username:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
  UserPut:
    type: "object"
    properties:
      username:
        type: "string"
      email:
        type: "string"
  ResetPassword:
    type: "object"
    properties:
      message:
        type: "string"
      token:
        type: "string"
  UserBio:
    type: "object"
    properties:
      username:
        type: string
      biography:
        type: string
  UserFollow:
    type: "object"
    properties:
      username:
        type: "string"
  passwordChange:
    type: "object"
    properties:
      username:
        type: "string"
      password:
        type: "string"
  PostBody:
    type: object
    properties:
      layout:
        type: string
      title:
        type: string
      description:
        type: string
  PostEntity:
    type: object
    properties:
      id:
        type: string
      layout:
        type: string
      title:
        type: string
      description:
        type: string
      comments:
        type: array
      likes:
        type: array
      pictures:
        type: array
      tags:
        type: array


  Error:
    type: "object"
    properties:
      code:
        type: "integer"
      index:
        type: integer
      errmsg:
        type: "string"
      op:
        type: "array"
        items:
          type: "string"
